### ISSUE TITLE
Support: Why dark theme?

### ISSUE THREAD

**Issue by hkirsman** [LivelyDismay/Learn-To-Mod#18]
Hi, could you explain this:

https://github.com/LivelyDismay/Learn-To-Mod/blob/main/lessons/Compiling%20a%20Modlist%20for%20Wabbajack.md

"Your copy of Mod Organizer 2 should be set to use a dark theme. This is both a courtesy to the people who will be installing your modlist"

Why is it courtesy if it's black? :)

**Comment by LivelyDismay** [comment]
It is a quick and easy indicator as to whether users have successfully finished the installation via Wabbajack.
